#
# TABLE STRUCTURE FOR: posts
#

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `community_id` int(10) unsigned DEFAULT NULL,
  `head` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `media_id` int(10) unsigned DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 1,
  `is_archived` tinyint(1) DEFAULT 0,
  `views_counter` int(10) unsigned DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (1, 100, 5, 'odio', 'Voluptatem corporis quasi rerum dicta sit. Quidem facere officia quos aut. Error nihil a cupiditate.', 92, 1, 0, 84, '1998-05-19 12:58:54', '1981-10-31 04:40:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (2, 84, 4, 'consequatur', 'Omnis in distinctio assumenda sunt veritatis. Nihil possimus voluptates itaque dolorem rem qui doloribus. Accusamus iusto non velit necessitatibus explicabo aliquid. Est quos consequatur maxime impedit et rem.', 50, 1, 0, 17, '1996-06-16 13:28:53', '1988-04-21 07:05:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (3, 99, 0, 'blanditiis', 'Quo blanditiis est cumque nesciunt. Perferendis quod distinctio repudiandae similique quia. Nostrum dignissimos aut nobis. Quo suscipit iure sapiente aut aut iste possimus.', 4, 1, 1, 48, '1988-12-09 00:22:16', '1984-10-26 13:47:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (4, 42, 5, 'qui', 'Nobis maxime saepe vel quibusdam ut explicabo velit. Similique nemo iure quis sunt. Consequuntur quod ea excepturi velit ducimus. Corrupti rem ut consequuntur quia velit eligendi.', 83, 1, 1, 3, '1977-06-04 09:32:43', '1971-08-05 19:23:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (5, 19, 1, 'fugiat', 'At aliquid voluptate esse a. In et illo maxime eum autem dolor. Distinctio dolor rerum necessitatibus explicabo ut harum aut.', 5, 1, 1, 12, '1988-10-12 12:16:06', '1975-04-02 08:36:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (6, 34, 0, 'quia', 'Cupiditate quia magnam minima ad quas in. Totam eos reiciendis soluta aut quam. Fuga ut molestiae eum id repudiandae totam sunt ullam. Commodi natus eius sed placeat.', 43, 0, 0, 15, '1970-09-14 12:14:06', '1970-07-04 13:50:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (7, 64, 3, 'mollitia', 'Quo nostrum qui sequi molestiae sint dolorem doloremque. Ea possimus illum eos aut. Beatae deserunt enim voluptatem dolor nisi neque voluptate delectus.', 59, 0, 1, 98, '2008-05-17 20:29:31', '1993-02-20 22:23:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (8, 85, 4, 'est', 'Nisi nobis voluptate distinctio. Et sed quia non et. Aut ut omnis nihil. Rerum repudiandae qui voluptatem.', 9, 0, 1, 12, '2012-11-11 09:22:49', '2016-01-10 07:22:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (9, 63, 2, 'ut', 'Quia quod autem qui blanditiis et dolor natus. Ut optio veritatis ut nostrum ad qui aut inventore. Illum et ducimus modi et qui.', 79, 1, 1, 31, '2012-12-23 23:58:04', '1977-08-23 02:03:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (10, 96, 0, 'natus', 'Eum expedita eos earum quia nobis. Voluptatum vel nesciunt omnis consequatur nostrum laudantium. Ut et non esse provident voluptatem. Tempora quia dolor aliquid fugiat.', 2, 0, 0, 76, '1983-10-25 22:04:53', '2006-08-06 08:15:10');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (11, 96, 0, 'quam', 'Et ipsa eos laudantium debitis sunt non quia. Nulla omnis omnis aut quas cupiditate. Excepturi rerum voluptatibus molestiae. Amet veniam consectetur corporis hic aut officiis. In totam velit sint autem.', 19, 0, 1, 15, '1974-06-02 21:45:11', '1986-04-30 16:00:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (12, 69, 3, 'magnam', 'Consequatur placeat error recusandae perspiciatis fugit. Optio repellendus necessitatibus dolores quis iusto. Officia omnis fugiat fugiat rerum aperiam aut ea enim. Quas reiciendis exercitationem odit ut.', 94, 0, 1, 15, '1975-01-18 20:31:39', '1995-01-05 22:22:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (13, 46, 2, 'architecto', 'Earum facilis officiis non voluptatum natus et sed eum. Placeat qui corrupti voluptatem quis atque velit optio. Autem quia eveniet odit sapiente et sed. Numquam soluta quo occaecati id.', 9, 1, 0, 55, '1977-10-01 17:59:30', '1979-02-25 17:33:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (14, 96, 2, 'mollitia', 'Ullam quod provident aut ut voluptas sed doloremque. Magnam doloribus in eligendi non. Laudantium atque officiis qui quis et. Omnis amet aut libero sunt harum.', 76, 1, 0, 35, '1972-05-15 11:30:26', '1976-10-10 22:45:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (15, 59, 1, 'dolore', 'Sunt doloribus molestiae officia nobis autem. Quidem non magnam aut repudiandae aut dolorem. Modi consectetur deleniti soluta eligendi nihil.', 64, 1, 1, 31, '1985-01-24 14:55:28', '2019-07-03 16:41:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (16, 12, 2, 'nihil', 'Beatae voluptate quasi quo et. Et repellat inventore est alias aspernatur optio. Ut voluptas omnis provident molestiae veritatis. Maiores ut reiciendis sapiente velit facilis voluptas corporis.', 1, 1, 1, 80, '2005-03-16 13:00:23', '2004-01-26 11:57:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (17, 25, 5, 'nobis', 'Rem tempore voluptatem quis vel. Dolorum doloribus fugiat ipsa deleniti qui impedit vitae. Enim aut sit maiores aspernatur. Provident expedita sit explicabo vero qui odio adipisci.', 10, 1, 0, 94, '2007-01-14 11:19:00', '1982-12-06 02:50:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (18, 3, 2, 'voluptatibus', 'Hic aspernatur enim ratione quisquam dolor perferendis consequatur nesciunt. Rerum sed fugit ullam totam. Cumque odio iure maiores nihil officiis.', 82, 0, 0, 1, '2007-07-10 07:04:07', '1987-06-20 11:23:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (19, 51, 4, 'et', 'Omnis voluptate non placeat praesentium quas non totam. Unde a voluptatem nihil laboriosam consequatur sit. Laudantium doloremque dolores quo hic.', 3, 0, 0, 90, '1973-09-07 16:39:40', '2004-10-21 20:02:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (20, 99, 0, 'ipsum', 'Praesentium ut asperiores eos placeat. Amet quos commodi quia quia ut consectetur. Eum aspernatur laudantium eos aliquid.', 19, 1, 1, 65, '2011-08-04 23:40:58', '2000-09-05 23:25:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (21, 1, 0, 'a', 'Molestias distinctio suscipit architecto qui dolore quidem quaerat. Et repellendus illum facilis dolores. Qui rerum omnis similique vel possimus est illo.', 20, 1, 1, 69, '1988-10-06 01:40:35', '2000-06-13 01:10:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (22, 6, 3, 'alias', 'Quas ut et et aut possimus quis nemo esse. Excepturi quia id enim aut accusantium ut. Saepe magni saepe dignissimos nulla dolorem rerum harum.', 88, 1, 1, 23, '1978-02-17 08:09:54', '1989-01-25 20:52:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (23, 16, 3, 'commodi', 'Libero libero totam saepe dolor perspiciatis. Nostrum et tenetur soluta facilis. Corporis voluptas quis esse necessitatibus. Perspiciatis nihil at expedita magnam.', 87, 1, 1, 27, '1985-09-02 01:59:29', '1980-09-15 07:31:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (24, 4, 1, 'rerum', 'Qui assumenda ea libero error est quas. Voluptatem quia placeat voluptatibus ipsum voluptatem dicta atque nostrum. Autem voluptas nihil quae dolorem sed itaque. Amet nihil sed distinctio provident.', 55, 0, 1, 74, '2003-08-01 16:26:43', '1982-06-30 07:09:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (25, 100, 2, 'velit', 'Autem dolore atque quia expedita. Voluptates alias necessitatibus ea magni culpa. Qui repellat eligendi temporibus non est dignissimos accusantium sed.', 71, 0, 1, 48, '2014-04-04 11:41:06', '1987-03-23 00:54:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (26, 91, 2, 'voluptas', 'Veniam nam unde dolor. Repellat et enim eveniet quo sapiente delectus aut quidem. Ut voluptatem modi rem ut nostrum reiciendis in.', 7, 0, 1, 40, '1976-10-29 12:46:52', '1986-11-14 23:16:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (27, 46, 2, 'molestiae', 'Et vitae consequatur natus. Sint quaerat rem accusantium sit excepturi. Ab laborum ipsa eos aut et rerum magnam. Maxime sequi quos explicabo quia maiores reiciendis.', 25, 0, 1, 59, '2020-05-18 10:26:44', '1980-11-20 16:25:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (28, 24, 0, 'ut', 'Qui cumque accusamus quisquam et. Consectetur dignissimos est aut et est.', 4, 0, 1, 45, '2000-06-11 13:36:50', '1974-06-28 01:09:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (29, 80, 0, 'architecto', 'Dolores quo aliquam omnis quia modi. Veniam ut ut neque asperiores. Dolorem dolorem maxime dolores ex. Voluptas autem illo tenetur nemo qui voluptas.', 60, 1, 0, 13, '2008-01-27 19:00:52', '2019-08-30 20:31:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (30, 12, 0, 'accusamus', 'Mollitia aperiam aut quisquam quas possimus et et quisquam. Et alias numquam autem vel ut fugit. Reiciendis eligendi ut eos magni hic fugit totam. Officia soluta vel ad sit perferendis voluptates sit.', 79, 0, 1, 31, '2019-07-21 12:49:00', '1971-05-09 19:54:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (31, 24, 1, 'esse', 'Earum ducimus ipsam autem nostrum nobis quasi qui asperiores. Est sint aut nesciunt perspiciatis eveniet praesentium molestiae.', 69, 1, 0, 12, '1970-03-23 08:55:02', '1973-02-13 07:20:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (32, 76, 5, 'laboriosam', 'Unde non rem inventore porro ut enim. Deleniti molestiae consectetur atque laudantium praesentium in nihil. Qui nam vero eligendi sed reiciendis. Non aut nam quis repellendus dicta minus eligendi.', 99, 1, 1, 56, '2006-04-25 10:43:47', '2007-09-25 12:03:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (33, 89, 2, 'porro', 'Ut in aut porro numquam voluptates. Et ut unde dolor numquam dolor neque id. Tempora quos odit rerum eum. Officia occaecati reprehenderit tempore nisi tenetur.', 57, 0, 1, 65, '1975-06-16 16:25:03', '1995-03-15 14:56:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (34, 59, 5, 'architecto', 'Sit laborum hic id iusto. Tempore voluptatibus perspiciatis adipisci quidem. Et sit maxime numquam dicta amet consequatur eaque. Quod sit illo iusto vel nesciunt qui necessitatibus.', 11, 0, 0, 11, '2010-12-20 12:09:40', '1998-07-20 03:24:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (35, 84, 2, 'facere', 'Reiciendis qui in natus architecto consequuntur odio. Quae fuga hic sapiente. Optio aliquid consequatur odit omnis.', 40, 1, 1, 41, '1974-01-19 21:29:07', '1987-02-02 12:25:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (36, 68, 1, 'quaerat', 'Quis non vitae deserunt. Dolorem voluptas explicabo ex id sunt et. Amet rem nihil maxime quaerat.', 91, 0, 1, 68, '2018-04-24 07:31:25', '1998-03-07 11:23:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (37, 61, 5, 'vel', 'Quisquam ratione voluptate inventore ut. Animi vitae nobis et fugiat et hic. Impedit eius incidunt beatae in sed totam. Nihil necessitatibus repellendus soluta.', 21, 0, 1, 17, '2015-03-05 18:21:44', '2017-03-30 17:09:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (38, 72, 4, 'est', 'Sunt vel consectetur sunt odit repellendus sed quia. Dolore porro voluptatem aut et. Ut amet ut non maxime dolorum voluptas.', 25, 1, 0, 74, '1997-05-05 01:36:15', '1993-04-13 12:44:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (39, 58, 1, 'nisi', 'Nostrum sed et odio architecto consequatur error sint. Consectetur magnam illo itaque eos. Autem error non beatae dolorem laboriosam.', 4, 0, 0, 57, '2009-07-01 08:32:05', '1997-04-17 17:27:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (40, 16, 0, 'quo', 'Ut quo eligendi incidunt impedit reiciendis. Suscipit sit aut id itaque repellat a dolore. Animi exercitationem quia et.', 77, 1, 0, 68, '1985-12-05 22:54:00', '1992-09-07 20:40:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (41, 45, 0, 'beatae', 'Numquam dolore deserunt dolores aut aut. Fugit est omnis id. Et minima ab omnis at. Culpa eum dolorem ut non neque sunt pariatur.', 92, 0, 0, 39, '2001-12-13 01:10:17', '1982-08-16 23:49:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (42, 38, 2, 'reprehenderit', 'Eum omnis a ratione. Quia distinctio deserunt cumque voluptatem qui libero illum. Et ducimus cupiditate ducimus eum voluptatem consectetur ut.', 94, 1, 0, 89, '2016-07-16 22:55:40', '2016-12-01 02:20:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (43, 87, 2, 'aspernatur', 'Quia rem et dignissimos dolorem repudiandae velit voluptas. Fuga expedita voluptas sit facilis eveniet ut aut. Et ut dolor nesciunt at aperiam. Quaerat sequi perspiciatis sed aperiam asperiores omnis.', 17, 0, 0, 63, '2008-04-08 21:50:58', '1984-10-18 02:28:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (44, 22, 0, 'ea', 'Sit sapiente ducimus sed nulla reprehenderit. Dolor aspernatur eum id. Quo quos ratione omnis consectetur.', 20, 1, 1, 14, '2008-10-31 18:09:15', '2003-02-01 07:50:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (45, 74, 2, 'harum', 'Eum occaecati laborum fuga placeat debitis et. Odit illum dicta quaerat earum. Reprehenderit alias totam ut aspernatur ut voluptatem facilis. Reiciendis aut necessitatibus accusamus illo quia.', 55, 1, 1, 54, '1983-04-11 09:35:23', '2020-03-03 16:01:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (46, 49, 5, 'numquam', 'Est vel sequi cupiditate dolorum modi aliquid error. Ipsam itaque nemo ad error et distinctio omnis possimus. Vel dignissimos nam nostrum tempore et sint nihil in. Vel est ut alias qui est molestiae ab. Voluptas nisi voluptatem dolorum quae enim aliquid.', 50, 1, 0, 50, '1978-11-10 21:58:16', '2002-02-20 13:23:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (47, 16, 0, 'ipsum', 'Voluptas nihil dolorem possimus cum iure cumque accusamus. Quasi quia praesentium dolor reprehenderit sed et ratione. Quis autem neque et nesciunt reiciendis. Magnam hic ut ex eos.', 92, 0, 1, 80, '1990-06-07 20:29:33', '2008-05-17 13:58:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (48, 29, 3, 'recusandae', 'Dignissimos cumque iure aut velit consequatur. Odio at adipisci debitis tempore rerum et. Voluptas beatae blanditiis molestias minus debitis vitae vitae. Cumque doloremque fuga id iure omnis quis.', 2, 1, 1, 69, '1975-03-09 00:46:20', '1973-11-24 05:03:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (49, 32, 1, 'magni', 'Molestiae neque animi est ratione. Labore consequatur dolorem repellendus ratione. Molestiae velit est quaerat voluptates ratione ea fugit.', 81, 0, 1, 22, '1978-10-30 06:59:44', '2019-01-09 08:14:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (50, 73, 4, 'mollitia', 'Nisi deserunt a amet nisi. Eos laboriosam reiciendis praesentium. Quis quia perspiciatis alias in.', 82, 0, 1, 0, '2009-12-21 19:28:05', '1992-01-25 07:46:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (51, 29, 3, 'sed', 'Ipsa quia aut voluptatem non aspernatur. Et autem fuga voluptatem rem dolorum ut. Magni voluptatem rerum nulla provident nemo ut officiis.', 91, 1, 1, 70, '1981-03-11 17:16:46', '1988-10-29 11:55:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (52, 65, 5, 'voluptatem', 'Id amet ea ea aut. Sunt est ea totam omnis est et assumenda. Odit facere natus praesentium debitis ea aut autem quo. Blanditiis eaque adipisci velit iste iusto.', 91, 1, 0, 64, '1987-11-17 09:24:24', '2015-05-05 08:23:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (53, 85, 2, 'veniam', 'Dignissimos quis nam qui et aut sunt aperiam ut. Sit officiis ipsam ut facilis eos blanditiis. Est iusto rerum optio repudiandae. Quo aut velit mollitia fuga eius molestiae consequatur.', 26, 1, 1, 17, '1973-07-18 06:37:07', '2006-05-25 15:50:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (54, 57, 2, 'rerum', 'Dicta nemo vitae modi error qui. Ea repellendus sunt illum odit. Placeat necessitatibus omnis repudiandae minima reiciendis nesciunt saepe. Cupiditate quia deserunt rerum veritatis.', 61, 1, 1, 32, '1978-04-07 06:34:51', '1996-09-04 22:55:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (55, 24, 3, 'ratione', 'Commodi maxime hic illum laboriosam sint accusamus. Ullam ex ratione sint. Aut sit nemo ullam et ducimus. Ad quisquam dolor blanditiis debitis.', 98, 1, 0, 57, '2018-11-04 07:04:17', '2013-09-18 16:28:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (56, 17, 3, 'minima', 'Vel doloremque maxime similique voluptas consequatur illo. Aut qui fuga quis ad aut. Veniam doloremque est tempore ea voluptas sint.', 59, 1, 0, 60, '2018-11-18 08:36:49', '1970-03-10 19:54:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (57, 38, 3, 'omnis', 'Ut consequatur repudiandae dolor qui sit aspernatur ea. Porro dolore quae quibusdam quis in error voluptatibus. Similique ut porro minima quia impedit fugit non.', 48, 1, 0, 30, '2002-07-13 19:26:44', '2004-10-15 01:20:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (58, 96, 0, 'blanditiis', 'Quo vero quidem nihil voluptatem. Deserunt excepturi fugiat minus libero fugiat iste. Vel a officiis libero maiores facilis. Est ipsam similique sed labore veritatis quo.', 35, 1, 0, 77, '1982-05-17 13:36:11', '1985-02-19 15:30:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (59, 86, 1, 'possimus', 'Tempore dolor libero vel rem libero id. Itaque sed illo dolores harum eos aliquam. Nobis suscipit voluptate aperiam reprehenderit consequatur. Modi consequatur asperiores quis quasi aut consectetur et.', 14, 1, 0, 65, '2013-01-05 13:36:08', '1983-11-04 13:58:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (60, 62, 0, 'vel', 'Placeat et est dolorum enim sunt. Quis ipsam ex vero eos et est iste tenetur. Vel et provident quod ut expedita est.', 40, 1, 0, 31, '1997-01-24 23:34:07', '1992-08-12 18:44:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (61, 41, 1, 'dolorem', 'Ea rerum animi consequatur aut voluptatem. Aut voluptate rerum exercitationem asperiores quasi ipsa voluptas.', 25, 0, 1, 89, '1992-07-17 23:27:28', '1995-12-02 10:18:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (62, 31, 0, 'minus', 'Eum sed quod maxime. Voluptates molestias voluptatum maiores consequatur. Nesciunt qui itaque velit qui. Ut nam corrupti numquam voluptatem nisi aut saepe.', 77, 1, 1, 12, '1983-12-26 02:57:50', '1976-08-20 01:00:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (63, 66, 0, 'corrupti', 'Nisi voluptatem aliquam assumenda id porro quia. Enim quam ut adipisci qui aut laudantium.', 72, 1, 1, 13, '1980-12-06 13:44:03', '2018-11-16 23:54:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (64, 53, 3, 'est', 'Sapiente rerum eligendi quasi distinctio neque dignissimos eaque. In sed aut et ullam. Vel omnis eos impedit eius placeat aperiam cum.', 83, 0, 0, 82, '2005-08-27 04:01:07', '1999-12-30 21:18:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (65, 58, 0, 'consequuntur', 'Iusto dolores dolores nesciunt molestiae. Voluptas laudantium dolorem ut nihil aspernatur nihil. Aut sunt illum fugiat odit itaque. Aliquid deleniti illum hic sit.', 9, 0, 1, 20, '1980-03-22 14:21:13', '1979-07-18 06:27:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (66, 54, 3, 'possimus', 'Maiores saepe dicta enim similique delectus magni. Voluptatem aliquid nihil eos ullam. At exercitationem ea nemo aspernatur quasi ut. Qui laborum sunt officiis ducimus aut architecto fugiat. Molestias accusantium provident saepe omnis velit qui.', 16, 0, 1, 97, '1972-07-01 22:08:33', '2013-05-20 09:46:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (67, 3, 5, 'sed', 'Perspiciatis consequatur tempore quod dolores. Earum temporibus corrupti eius aut architecto est. Quos laboriosam nisi sint molestias consequatur. Fugiat molestiae consequuntur fugit sit dolorem unde.', 70, 1, 0, 99, '2019-03-08 21:49:21', '1977-07-28 21:31:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (68, 36, 2, 'aut', 'Qui odit vero similique a pariatur cum. Et cupiditate nobis accusantium. Expedita ab consequuntur et aut sed dicta quasi. Ullam expedita nihil et optio doloribus.', 66, 0, 0, 64, '1971-09-21 14:32:04', '1975-03-11 02:11:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (69, 52, 5, 'odio', 'Beatae magnam omnis magni iure nesciunt. Eligendi explicabo iste qui quia esse. Blanditiis omnis et libero minus optio. Voluptates occaecati officia reiciendis quis a in libero.', 52, 0, 0, 16, '2000-06-24 06:19:05', '2019-03-14 06:39:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (70, 58, 4, 'dolores', 'Ut animi aspernatur eum nostrum quaerat eius. Et ducimus adipisci consectetur quasi consequatur. Nisi exercitationem in numquam.', 9, 1, 0, 24, '1977-06-26 05:51:51', '1984-11-19 17:22:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (71, 13, 2, 'corporis', 'Dolore laboriosam voluptas accusamus minima modi dolore accusamus explicabo. Voluptatum eligendi consequatur vel. Dolor mollitia illo vitae veniam qui distinctio voluptatem. Enim et blanditiis asperiores ex ut et nisi minus. Et sunt et earum et rerum sunt dolorum.', 17, 0, 1, 3, '1993-03-09 21:49:15', '1998-09-23 05:19:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (72, 44, 2, 'et', 'Odit voluptas dolorem perferendis asperiores aperiam cupiditate voluptate. Quo sint ea eligendi minus qui tenetur porro. Eius cupiditate officia vitae et.', 59, 0, 1, 59, '2000-07-11 09:17:32', '2005-06-26 05:24:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (73, 95, 1, 'neque', 'Quo voluptate delectus numquam eveniet veritatis alias voluptas. Ullam sed ab ut quo. In ut in qui repudiandae soluta. Hic qui libero atque molestiae excepturi enim.', 93, 1, 1, 56, '2012-10-16 23:39:02', '2009-02-24 18:10:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (74, 63, 3, 'repellat', 'Quo facere neque et excepturi vero dolorem voluptas. Consequatur error sint dignissimos accusamus corrupti. Sed nam vero rerum et sint voluptas et.', 66, 0, 1, 28, '1984-04-20 22:51:50', '1977-03-25 11:33:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (75, 12, 5, 'voluptatem', 'Eius temporibus est atque sed. Commodi modi molestias quia est quae et aut fugit. Laudantium aperiam eaque aliquid qui. Praesentium laboriosam aut quo sunt delectus et blanditiis.', 70, 0, 0, 72, '2016-06-05 20:57:28', '1983-03-03 10:47:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (76, 17, 4, 'totam', 'Est officiis laudantium beatae rerum. Quisquam pariatur aut in maiores impedit. Cum amet officia dicta iure quae asperiores.', 29, 0, 0, 63, '1986-02-16 09:43:14', '1997-05-25 12:21:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (77, 98, 1, 'cumque', 'Illo incidunt sed nisi animi. Quia quia consectetur dolor earum corporis. Error voluptatem sapiente magnam nemo.', 96, 1, 0, 35, '1996-04-10 12:39:43', '1998-01-14 08:31:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (78, 70, 3, 'hic', 'Quasi nulla sed quia aut. Odio omnis sed ipsam sed sed facilis.', 82, 0, 1, 52, '2013-06-07 11:59:08', '1988-10-25 15:17:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (79, 80, 0, 'magni', 'Ut alias quod perspiciatis iste esse. Reiciendis qui totam asperiores sit eveniet et et.', 61, 0, 1, 44, '1973-12-19 18:52:37', '2018-02-08 18:42:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (80, 49, 1, 'eum', 'Numquam soluta ut porro vel. Laudantium reiciendis quod qui alias est cum. Rem aperiam excepturi eos odio ratione.', 14, 0, 0, 18, '1995-08-19 10:10:57', '1980-07-17 18:15:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (81, 19, 2, 'quis', 'Provident harum voluptatum nihil quis eum dolor. Exercitationem hic labore ut odio provident. Dignissimos voluptatibus fugit praesentium possimus enim eaque quibusdam.', 21, 0, 1, 84, '1988-11-26 08:08:36', '1999-10-04 15:15:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (82, 94, 5, 'enim', 'Ipsum magnam accusantium explicabo et temporibus. Exercitationem dolorem libero vel. Id tempora possimus molestiae consequatur reprehenderit.', 9, 1, 1, 42, '2020-02-08 11:39:46', '1979-07-30 10:23:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (83, 99, 4, 'dolor', 'Neque dolores ut eum minima nostrum velit ipsa. Cum rerum quibusdam sed magnam molestias et. Sapiente pariatur optio voluptatem qui. Autem et corporis esse qui delectus enim.', 93, 0, 0, 25, '2015-10-18 10:08:56', '1977-11-12 17:52:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (84, 42, 1, 'aut', 'Quidem ab fugit libero veritatis dolores dolorem. Deleniti quia ut non. Ipsa cumque corrupti quo.', 77, 0, 1, 44, '1984-12-03 02:36:12', '2016-11-26 19:50:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (85, 17, 4, 'nihil', 'Adipisci dolores eum et consectetur incidunt expedita est. Quia nihil pariatur reprehenderit similique. Porro sint voluptate ab dolorem. Quo et ut qui ipsa ipsa nemo.', 68, 0, 1, 19, '1977-05-26 00:29:44', '2011-10-06 23:28:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (86, 18, 5, 'omnis', 'Eveniet blanditiis tenetur esse quia. Minus quidem fuga omnis et neque. Ut eos ullam consequatur nostrum culpa.', 54, 0, 1, 46, '2006-01-31 19:51:07', '1979-12-04 23:46:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (87, 82, 5, 'laudantium', 'Vel quibusdam totam tempora iste. Quibusdam accusantium odio facere vitae iure. Ut perspiciatis quos nisi quisquam laborum tenetur aspernatur.', 23, 0, 0, 45, '1989-01-23 03:14:15', '1977-12-26 22:48:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (88, 57, 0, 'atque', 'Rerum ea quo quia iure aut. Ab vel saepe pariatur eaque est est aperiam.', 66, 1, 1, 11, '1985-02-15 13:11:06', '2019-05-01 12:56:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (89, 44, 5, 'quibusdam', 'Et tempore maiores ratione tempora. Qui velit sit ea nesciunt soluta earum nobis. Voluptate nobis aut et autem ullam. Sed aut iure laudantium.', 18, 1, 1, 10, '2017-03-26 15:29:17', '2020-04-22 06:13:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (90, 84, 1, 'quia', 'Quasi illo qui rerum sint aut dolores. Animi velit et cum omnis eius repudiandae est debitis. Et fugit voluptatem occaecati laudantium.', 96, 1, 1, 35, '1995-10-20 04:38:18', '1999-02-23 16:11:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (91, 81, 1, 'recusandae', 'Quo dolores voluptatem quis velit ea et pariatur. Quia voluptas natus officia nobis ipsa. Voluptatem ex repellendus adipisci architecto quas ea.', 88, 0, 1, 19, '1992-04-25 20:53:37', '2010-09-16 14:17:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (92, 1, 2, 'fugiat', 'Ut voluptate eveniet fugiat quam quia accusamus est. Natus qui qui nobis voluptatem. Ea doloribus error enim similique qui in.', 54, 0, 0, 87, '2007-04-01 23:07:53', '2001-11-08 03:10:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (93, 86, 1, 'sit', 'Laborum omnis sint repudiandae. Quasi iusto ullam quia nihil et. Culpa id ut fugit. Quia beatae vero corrupti error incidunt.', 69, 0, 1, 88, '1974-07-01 00:11:04', '2011-05-27 19:50:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (94, 57, 5, 'harum', 'Veniam accusantium suscipit voluptatem expedita voluptate aut. Quia perspiciatis quas aperiam aspernatur vero nostrum. Sed architecto ipsam excepturi eum possimus et enim est.', 47, 0, 0, 9, '1993-09-06 22:58:47', '2007-05-11 12:44:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (95, 61, 1, 'voluptatem', 'Ex sed omnis et asperiores est. Non iusto blanditiis ab ducimus dolores est soluta aut. Earum aliquid reiciendis ut culpa illum.', 30, 1, 0, 40, '1986-05-21 20:42:29', '2002-04-06 10:38:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (96, 89, 0, 'ipsa', 'Porro voluptatem eaque et. Ex ex est sed ex provident porro. Distinctio deleniti fugit praesentium ut eveniet accusantium.', 63, 1, 0, 12, '1979-08-31 20:07:37', '2001-10-31 04:34:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (97, 16, 5, 'delectus', 'Ut amet maiores id placeat exercitationem. Voluptas tempore omnis fuga molestiae dignissimos. Voluptas quia earum cupiditate omnis nemo possimus. Et qui illum rerum et.', 81, 1, 0, 49, '2003-11-11 21:35:23', '1976-02-18 11:15:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (98, 68, 1, 'iste', 'Beatae consequatur fuga corporis voluptatibus magnam. Hic harum rerum in ex. Facilis reprehenderit aut quidem et error non consequuntur adipisci. Reprehenderit iure nisi est eligendi. Voluptatem nemo minus eligendi ea.', 93, 1, 0, 47, '2012-10-10 21:29:39', '2011-12-28 21:55:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (99, 94, 5, 'voluptas', 'Consectetur et consectetur libero consequuntur cumque magnam. Beatae molestiae nobis nisi repellendus delectus voluptatem.', 85, 1, 0, 0, '2014-12-29 13:55:21', '1975-07-08 21:09:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `views_counter`, `created_at`, `updated_at`) VALUES (100, 92, 0, 'consequatur', 'Est aliquam aliquam et sit. Praesentium voluptatem non corporis exercitationem laboriosam occaecati quisquam. Veritatis quisquam praesentium voluptas magnam.', 56, 1, 0, 94, '2013-09-17 20:04:20', '2016-08-01 00:48:41');


